DefaultContentLanguage = "es"

baseURL = "https://asur.dev"

theme = "amperage"

pygmentsUseClasses = true

[languages]
    [languages.es]
        contentDir = "content"
        languageName = "Español"
        languageCode = "es"
        title = "Un blog by Asur 🧐"
        description = "Bienvenid@ a mi blog, si te gusta el desarrollo web, el SEO, el open source y la tecnología en general echa un vistazo, seguro que encuentras algo interesante!"
        weight = 1
    [languages.en]
        contentDir = "content/english"
        languageName = "English"
        languageCode = "en"
        title = "A blog by Asur 🧐"
        description = "Welcome to my blog, if you like web development, SEO, open source and technology in general have a look, you may find something interesting!"
        weight = 2

[[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/asurbernardo"
    weight = 10
[[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/asurbernardo"
    weight = 10
[[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/asur-bernardo/"
    weight = 10

[taxonomies]
    tag = "tags"

[params]
    copyright = "asur.dev"
    themeColor = "#333"

    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker", "amp-iframe"]

    adsensePublisher = "ca-pub-8268925024957381"
    googleAnalytics = "UA-128498798-1"
    commentsEmbedUrl = "https://comments.asur.dev"

    facebookSite = "asur.dev"
    twitterSite = "@asurbernardo"
    socialProfiles = ["https://twitter.com/asurbernardo","https://www.linkedin.com/in/asur-bernardo/","https://github.com/asurbernardo","https://stackoverflow.com/users/4524353/asur"]

    alternatePageName = "asur.dev"
    organizationLogo = "/logo.png"
    organizationName = "Asur"

    publisherName = "Asur Bernardo"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60