baseURL = "https://asur.dev"

languageCode = "es"

title = "Bienvenid@ a mi blog | By Asur 🧐"

theme = "amperage"

pygmentsUseClasses = true

[taxonomies]
    tag = "tags"

[params]

    description = "Bienvenid@ a mi blog, si te gusta el desarrollo web, el SEO, el open source y la tecnología en general echa un vistazo, seguro que encuentras algo interesante."

    themeColor = "#ef8b80"

    adsensePublisher = ""
    googleAnalytics = "UA-128498798-1"

    ampElements = ["amp-analytics", "amp-social-share"]

    alternatePageName = "Blog de Asur"
    organizationLogo = "/logo.png"
    organizationName = "Asur"
    organizationAddress = ""

    facebookSite = "asur.dev"
    twitterSite = "@asurbernardo"

    socialProfiles = ["https://twitter.com/asurbernardo","https://www.linkedin.com/in/asur-bernardo/","https://github.com/asurbernardo","https://stackoverflow.com/users/4524353/asur"]

    publisherName = "Asur Bernardo"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60