DefaultContentLanguage = "es"

baseURL = "https://asur.dev"

theme = "amperage"

pygmentsUseClasses = true

[languages]
    [languages.es]
        contentDir = "content"
        languageName = "Español"
        languageCode = "es"
        title = "Bienvenid@ a mi blog | By Asur 🧐"
        description = "Bienvenid@ a mi blog, si te gusta el desarrollo web, el SEO, el open source y la tecnología en general echa un vistazo, seguro que encuentras algo interesante."
        weight = 1
    [languages.en]
        contentDir = "content/english"
        languageName = "English"
        languageCode = "en"
        title = "Welcome to my blog | By Asur 🧐"
        description = "This is the English section of my site. It's still work in progress but hey news are coming! Stay tuned!"
        weight = 2

[[menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/asur-bernardo/"
    weight = 10
[[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/asurbernardo"
    weight = 10
[[menu.main]]
    identifier = "stackoverflow"
    name = "StackOverflow"
    url = "https://stackoverflow.com/users/4524353/asur"
    weight = 10
[[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/asurbernardo"
    weight = 10

[taxonomies]
    tag = "tags"

[params]
    themeColor = "#ef8b80"

    ampElements = ["amp-analytics", "amp-social-share", "amp-install-serviceworker"]

    adsensePublisher = ""
    googleAnalytics = "UA-128498798-1"

    facebookSite = "asur.dev"
    twitterSite = "@asurbernardo"
    socialProfiles = ["https://twitter.com/asurbernardo","https://www.linkedin.com/in/asur-bernardo/","https://github.com/asurbernardo","https://stackoverflow.com/users/4524353/asur"]

    alternatePageName = "asur.dev"
    organizationLogo = "/logo.png"
    organizationName = "Asur"

    publisherName = "Asur Bernardo"
    publisherLogo = "/logo-amp-article.png"
    publisherLogoWidth = 600
    publisherLogoHeight = 60