baseURL = "https://asurbernardo.com"

languageCode = "es"

title = "Bienvenid@ a mi blog | By Asur 🧐"

theme = "amperage"

pygmentsUseClasses = true

[taxonomies]
    tag = "tags"

[params]
    adsensePublisher = ""
    googleAnalytics = ""
    
    alternatePageName = "Blog de Asur"
    organizationLogo = ""
    organizationName = ""
    organizationAddress = ""

    socialProfiles = ["https://www.facebook.com/your-profile","http://instagram.com/yourProfile"]
    
    publisherName = ""
    publisherLogo = ""
    publisherLogoWidth = 600
    publisherLogoHeight = 60