baseURL = "https://asurbernardo.com"
languageCode = "es"
title = "Bienvenido a mi blog"
theme = "amperage"

[params]
    adsensePublisher = ""
    googleAnalytics = ""
    
    alternatePageName = ""
    organizationLogo = ""
    organizationName = ""
    organizationAddress = ""

    socialProfiles = ["https://www.facebook.com/your-profile","http://instagram.com/yourProfile"]
    
    publisherName = ""
    publisherLogo = ""
    publisherLogoWidth = 600
    publisherLogoHeight = 60